
//el archivo sirve para la vinculacion de firebase con el proyecto flutter, se genera automaticamente al crear el proyecto en firebase y descargar el archivo google-services.json

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions { 
  // sirve para definir las opciones de configuracion de firebase para cada plataforma
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJncSksaLbepg7mC03qQ313E1BCgjM1bI',
    appId: '1:638752494916:web:8bd277aa851c210d917311',
    messagingSenderId: '638752494916',
    projectId: 'oculist-sistema-inteligente',
    authDomain: 'oculist-sistema-inteligente.firebaseapp.com',
    storageBucket: 'oculist-sistema-inteligente.firebasestorage.app',
    measurementId: 'G-3JT7RZH7WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJRQvBqELA4PpzZkyjloMRC0nnJ3ds6IU',
    appId: '1:638752494916:android:72fabc5db98d4d7f917311',
    messagingSenderId: '638752494916',
    projectId: 'oculist-sistema-inteligente',
    storageBucket: 'oculist-sistema-inteligente.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUcus5WycCWoMWaIdQgYB9W7HnHgi8n0',
    appId: '1:638752494916:ios:362c9c1c16bb65b6917311',
    messagingSenderId: '638752494916',
    projectId: 'oculist-sistema-inteligente',
    storageBucket: 'oculist-sistema-inteligente.firebasestorage.app',
    iosBundleId: 'com.example.oculist',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUcus5WycCWoMWaIdQgYB9W7HnHgi8n0',
    appId: '1:638752494916:ios:362c9c1c16bb65b6917311',
    messagingSenderId: '638752494916',
    projectId: 'oculist-sistema-inteligente',
    storageBucket: 'oculist-sistema-inteligente.firebasestorage.app',
    iosBundleId: 'com.example.oculist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJncSksaLbepg7mC03qQ313E1BCgjM1bI',
    appId: '1:638752494916:web:cf882682ec9724a2917311',
    messagingSenderId: '638752494916',
    projectId: 'oculist-sistema-inteligente',
    authDomain: 'oculist-sistema-inteligente.firebaseapp.com',
    storageBucket: 'oculist-sistema-inteligente.firebasestorage.app',
    measurementId: 'G-PMGHYG597S',
  );
}
